# Generated by Django 2.0.10 on 2019-02-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190226_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Advisor'), (3, 'Approver'), (4, 'Mentor')], default=1),
        ),
    ]
