# Generated by Django 2.0.10 on 2019-03-04 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190227_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Faculty of Engineering'), (2, 'Faculty of Law'), (3, 'Faculty of Economy'), (4, 'Faculty of Philosophy')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='linked_in',
            field=models.URLField(null=True),
        ),
    ]
