# Generated by Django 2.0.10 on 2019-03-03 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190302_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='GPA',
        ),
        migrations.AddField(
            model_name='profile',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Faculty of Engineering'), (2, 'Faculty of Law'), (3, 'Faculty of Education')], null=True),
        ),
    ]
