# Generated by Django 2.0.10 on 2019-04-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_auto_20190406_1225'),
        ('users', '0006_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_control',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access_control.AccessControl'),
        ),
    ]
