# Generated by Django 2.0.10 on 2019-04-06 12:25
import json
from django.db import migrations

from sdu_beta_career.access_control.config import ACCESS_CONTROLS


def create_default_access_controls(apps, schema_editor) -> None:
    """
    Simple function creating/updating AccessControls.

    Should be called in migration explicitly for any changes of config.ACCESS_CONTROLS.
    """
    AccessControl = apps.get_model("access_control", "AccessControl")
    for name, controls in ACCESS_CONTROLS.items():
        ac_object, created = AccessControl.objects.get_or_create(name=name)
        ac_object.controls = controls
        ac_object.save()


class Migration(migrations.Migration):
    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_access_controls, migrations.RunPython.noop)
    ]
